XMLM-19: Invalid XML gives wrong error
mulesoft/mule-xml-module pull request #112
Opened 2021-11-16 21:07 UTC by giss-ignacio

Invalid XML gives TRANSFORMATION instead of INVALID_INPUT_XML error since release version 1.2.3

2021-11-17 17:54 UTC, juldiazmule submitted a review, later dismissed

2021-11-18 00:55 UTC, nicomz requested changes

2021-11-18 00:55 UTC, nicomz commented on out
> +[INFO] Scanning for projects...
Is this file necessary?

2021-11-18 01:05 UTC, giss-ignacio commented on out
> +[INFO] Scanning for projects...
oh no. thanks

2021-11-18 01:06 UTC, nicomz approved these changes

2021-11-18 01:13 UTC, merged