W-11909424 Add XML schema content validation feature
mulesoft/mule-xml-module pull request #138
Opened 2022-11-30 09:26 UTC by rogerwang1102

Add XML schema content validation feature which allows user to perform validation by entering schema text directly

2022-12-05 19:42 UTC, GuidoGianfrate requested changes

2022-12-05 19:42 UTC, GuidoGianfrate commented on src/main/java/org/mule/module/xml/api/SchemaContent.java
> +import java.util.Objects;
import order

2022-12-05 19:42 UTC, GuidoGianfrate commented on src/main/java/org/mule/module/xml/api/SchemaContent.java
> +
delete line 23

2022-12-05 19:42 UTC, GuidoGianfrate commented on src/main/java/org/mule/module/xml/api/SchemaContent.java
> +
delete line 29

2022-12-05 19:42 UTC, GuidoGianfrate commented on src/main/java/org/mule/module/xml/internal/error/SchemaInputException.java
> + * @since 1.0
Since 1.3.4

2022-12-05 19:42 UTC, GuidoGianfrate commented on src/main/java/org/mule/module/xml/internal/error/SchemaInputException.java
> +
delete line 27

2022-12-05 19:42 UTC, GuidoGianfrate commented on src/main/java/org/mule/module/xml/internal/operation/SchemaValidatorOperation.java
> +    //perform check on schema location field and schema content field, only one can be used and must provided.
I think is better put this comment where is located the private method, in the line 167 of this class

2022-12-05 20:39 UTC, waltercardozo commented on src/main/java/org/mule/module/xml/internal/operation/SchemaValidatorOperation.java
> +  private boolean isBlank(String value) {
You can use Google Guava Strings.isNullOrEmpty()

2022-12-05 20:55 UTC, waltercardozo requested changes

2022-12-05 20:55 UTC, waltercardozo commented on src/main/java/org/mule/module/xml/internal/operation/SchemaValidatorOperation.java
> +  private void checkSchemaInput(String schemas, List<SchemaContent> schemaContents) {
Keep the Operation class as clean as possible with the method operation only. You should create another class with the responsibility of validate schemas. Could be a Service or a SchemaValidator, for instance. We would win an easier testability for all validation functionality without running a mulesoft environment.

2022-12-06 14:40 UTC, GuidoGianfrate approved these changes

2022-12-07 13:50 UTC, waltercardozo approved these changes

2022-12-07 17:27 UTC, merged